### ISSUE TITLE
Hi, I have selected gl18-tl-resnet50-gem-w, how can I convert the vector dimension to 512?

### ISSUE THREAD

**Issue by ponponon** [gmberton/deep-visual-geo-localization-benchmark#18]
Hi, I have selected gl18-tl-resnet50-gem-w, how can I convert the vector dimension to 512?

By default, gl18-tl-resnet50-gem-w outputs a vector dimension of 2048, but what if I want to convert it to 512 dimensions? What should I do?

**Comment by gmberton** [comment]
Hi, you can add this after the model initialization
`model.module.aggregation[1] = torch.nn.Linear(2048, 512)`
which will change the whitening / linear layer (the pretrained model's layer has output 2048, the new one will be 512).
However note that the results will be quite lower, because the new layer will be randomly initialized.
