### ISSUE TITLE
A Nearest Neighbor Search Question

### ISSUE THREAD

**Issue by qin-yu-01** [gmberton/deep-visual-geo-localization-benchmark#30]
Good job!
But could you please tell me where the code for the nearest neighbor matching methods (such as PQ/IVF/PQIVF/HNSW, etc.) is located?

**Comment by gmberton** [comment]
Hi, we didn't include that code because it is trivial to change it. You can just change [the line of code with the faiss index](https://github.com/gmberton/deep-visual-geo-localization-benchmark/blob/main/test.py#L178) to include one of the faiss indexes from [this list](https://github.com/facebookresearch/faiss/wiki/Faiss-indexes). It should be as simple as adding 1 to 3 lines of code
