### ISSUE TITLE
[Questions] Input image size

### ISSUE THREAD

**Issue by zafirshi** [gmberton/deep-visual-geo-localization-benchmark#6]
Hi~ thx for your great work! :smile: 

I have a question about the size of the input image. 

I found that in the MSLS dataset, the size of the image is not completely consistent. Some images are large in size and some are small in size, which not has the same size as the Pitts-250k dataset.

So, I want to ask:   _How to deal with input images of different sizes during training?_

I would like to use ViT or other variant as backbone, as we all know ViT needs unified image input size(224*224), how to deal with large size input(e.g. 600*1200)? Direct resize image to uniform size will lose information and lead to poor results.

**Comment by gmberton** [comment]
Hello and thanks!
You are right, MSLS contains images of various sizes.
I'd say that there are two types of images:
1) some (very few) are wide panorama images. Following the original code from MSLS, these images are discarded for training. Specifically, we discard them while reformatting the dataset in [here](https://github.com/gmberton/datasets_vg/blob/main/format_mapillary.py#L41) (note that this code is in the repo that we use for downloading and reformatting the datasets).
2) all other images are "roughly" of dimension 480x640. I say roughly because while most are 480x640, there are also some images with similar resolution, like 360x640. For these images we simply resize them all to 480x640, again following the original code.
Regarding resizing for ViT, as long as database and queries undergo the same (slight) distortion, it shouldn't be a problem to resize the 480x640 images to 224x224

**Comment by zafirshi** [comment]
Thank you for your fast and detailed reply！I really appreciated!

If I want to use the Transformer architecture to process the small number of large field images, **it is obviously unreasonable to directly resize the images**. If I do not want to separate the panorama images, what good suggestions or methods are there to deal with these panorama images?

**Comment by gmberton** [comment]
Well that's a good question, I think it depends on many things... how big are the images? Do they all have the same direction? How much resources (GPU) do you have? If you want to do it for the panorama images of MSLS, I don't think it's very convenient because there are not many. If it is for some other dataset with panoramas, then there are a few things that can be done. Usually I prefer to split the into multiple crops, but it seems not to be an option for you

**Comment by gmberton** [comment]
Closed for inactivity
